### ISSUE TITLE
Trigger Code Issues

### ISSUE THREAD

**Issue by nickgang** [nickgang/dualpianoEEG#14]
Trigger codes are being sent incorrectly for the final 4 unison notes.

Workarounds for pilot data analysis:
For Human/Human condition - Select whichever trigger code came first/is present 174 or 74.

For Human/Max - Working on well-defined workaround for this

**Comment by matthewjameswright** [comment]
What codes are expected and what codes do you get instead?

**Comment by nickgang** [comment]
For the Human/Human condition, the trigger codes for those last 4 unison notes are supposed to be 74-77 for the odd player and 174-177 for the even player.

Right now they count up based on each players' note, meaning the player to play unison note #1 first will get a 74 or 174 and the player to play unison note #1 second will get a 75 or 175. This continues to count up until the last trigger code is 81 or 181 depending on who plays unison note #4 second.

**Comment by nickgang** [comment]
I will examine skynet a bit more and get back to you when I do.

**Comment by nickgang** [comment]
Just FYI, I have a few local commits right now trying to tackle this issue. I will test a little bit and push if it works.

**Comment by nickgang** [comment]
Checked in fixes for Human/Max conditions. Still looking into human/human counting by two bug.

**Comment by nickgang** [comment]
Just checking in a fix for the counting by two bug. I don't have two keyboards (or one big enough to split and play both both parts) so I'm waiting to test this before closing out the issue.

**Comment by nickgang** [comment]
Tested today, all trigger code issues with the 5th measure are fixed.
