### ISSUE TITLE
Spurious "out-of-turn-note" errors

### ISSUE THREAD

**Issue by nickgang** [nickgang/dualpianoEEG#2]
Out of turn note errors when playing is correct are currently keeping trials from being marked as correct. I suspect this issue comes from the old logic used in 'check-for-performance-errors' within 'check-errors-and-send-triggers' which still looks for the old phrase number (1-6).

**Comment by matthewjameswright** [comment]
It's not the change in phrase numbering; the duplicated code solution never worked.

**Comment by matthewjameswright** [comment]
Reverted buggy duplicated code attempt in check-for-performance-errors; this problem now gone.
