### ISSUE TITLE
Simultaneous Notes Incorrectly Marked as Errors

### ISSUE THREAD

**Issue by nickgang** [nickgang/dualpianoEEG#7]
In Human/Human and Human/Max blocks, the notes played simultaneously will always be marked as errors. It seems that Max throws both a "wrong note" erro for all notes and "bad IOI" error for only a few notes. Attached is a screen shot from block 6 (Human/Human, P1 even).
![max_error_1](https://cloud.githubusercontent.com/assets/15150422/13368910/f004245c-dca3-11e5-9cb4-02fc9ee184b4.png)

**Comment by nickgang** [comment]
Latest change fixes the incorrect "wrong note" errors. It still appears as though the IOI is not being computed correctly starting with the second note of the simultaneous passage.

**Comment by matthewjameswright** [comment]
That was a side-effect of the off-by-one error; now fixed
